import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { auth, currentUser } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopNav() {
  const authObj = currentUser();
  console.log("hi");
  authObj.then((obj) => {
    console.log("user", obj?.fullName, obj?.imageUrl);
  });
  return (
    <nav className="flex w-full items-center justify-between p-4">
      <div>Pointing Poker</div>

      <div className="flex gap-4">
        <Link
          className="rounded bg-blue-500 px-2 py-1 font-bold text-white"
          href="/create"
        >
          Create
        </Link>
        <SignedOut>
          <Link href="/signin">Sign In</Link>
        </SignedOut>
        <SignedIn>
          <UserButton></UserButton>
        </SignedIn>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
